---
- name: Install epel repo
  yum: name=epel-release state=present

- name: Install packages
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - java
    - python-pip

- name: Check for Elasticsearch RPM Local Download
  stat: path=/vagrant/deps/{{ elasticsearch_package }}
  register: elastic_local_package

- name: Download Elasticsearch RPM
  get_url: url={{ elasticsearch_url }} dest=/vagrant/deps/{{ elasticsearch_package }}
  when: not elastic_local_package.stat.exists

- name: Install Elasticsearch
  yum: name=/vagrant/deps/{{ elasticsearch_package }}
